- bioimageio_core_version: 0.5.8
  bioimageio_spec_version: 0.4.9
  error: Not found any of the specified weights formats ['pytorch_script']
  name: load resource description
  nested_errors: null
  source_name: scripts/../bioimageio-gh-pages/rdfs/10.5281/zenodo.5910854/6539073/rdf.yaml
  status: failed
  traceback: ["  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/resource_tests.py\",
      line 202, in _test_load_resource\n    rdf, weights_priority_order=None if weight_format
      is None else [weight_format]\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/resource_io/io_.py\",
      line 55, in load_resource_description\n    raise ValueError(f\"Not found any
      of the specified weights formats {weights_priority_order}\")\n"]
  warnings: {}
