bioimageio_core_version: 0.5.1
bioimageio_spec_version: 0.4.5post3
error: Not found any of the specified weights formats ['pytorch_script']
name: reproduce test outputs with ilastik 1.4.0b26 using pytorch_script weights
reason: error
status: failed
traceback: ["  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/resource_tests.py\",
    line 39, in test_model\n    model_rdf, weights_priority_order=None if weight_format
    is None else [weight_format]\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/resource_io/io_.py\",
    line 49, in load_resource_description\n    raise ValueError(f\"Not found any of
    the specified weights formats {weights_priority_order}\")\n"]
