bioimageio_core_version: 0.5.1
bioimageio_spec_version: 0.4.5post3
error: cannot reshape array of size 1555318 into shape (1,1,32,360,360)
name: reproduce test outputs with ilastik 1.4.0b26 using pytorch_state_dict weights
reason: error
status: failed
traceback: ["  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/resource_tests.py\",
    line 126, in test_resource\n    inputs = [np.load(str(in_path)) for in_path in
    model.test_inputs]\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/resource_tests.py\",
    line 126, in <listcomp>\n    inputs = [np.load(str(in_path)) for in_path in model.test_inputs]\n",
  "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/numpy/lib/npyio.py\",
    line 441, in load\n    pickle_kwargs=pickle_kwargs)\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/numpy/lib/format.py\",
    line 787, in read_array\n    array.shape = shape\n"]
