bioimageio_core_version: 0.5.3post2
bioimageio_spec_version: 0.4.5post6
error: 'PytorchStreamReader failed reading zip archive: failed finding central directory'
name: reproduce test outputs with ilastik 1.4.0b27 using torchscript weights
reason: error
status: failed
traceback: ["  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/resource_tests.py\",
    line 148, in test_resource\n    bioimageio_model=model, devices=devices, weight_format=weight_format\n",
  "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/prediction_pipeline/_prediction_pipeline.py\",
    line 114, in __enter__\n    self.load()\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/prediction_pipeline/_prediction_pipeline.py\",
    line 172, in load\n    self._model.load()\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/prediction_pipeline/_model_adapters/_model_adapter.py\",
    line 41, in load\n    self._load(devices=devices or self.default_devices)\n",
  "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/prediction_pipeline/_model_adapters/_torchscript_model_adapter.py\",
    line 23, in _load\n    self._model = torch.jit.load(weight_path)\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/torch/jit/_serialization.py\",
    line 161, in load\n    cpp_module = torch._C.import_ir_module(cu, str(f), map_location,
    _extra_files)\n"]
